FROM ubuntu:latest
RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/* 
  ## && /bin/bash -c "while :; do wget -qO- https://talaikis.com/api/quotes/ random; printf '\n'; sleep 5; done"

